org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.configureondemand=true

mod.id=miaow
mod.name=miaow
mod.version=1.1.0
mod.group=cat.anya.miaow
mod.description=New keybinds let you miaow, hiss or purr. Crouch and miaow to sound like a stray.
